### PR TITLE
New release

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by affeldt-aist** [comment]
@erikmd Actually, I could double-check by myself so I merge without review. Sorry for the noise.

**Comment by erikmd** [comment]
Hi @affeldt-aist, sorry for late reply, but your PR was very fine!

Actually, the current issue is that we don't have enough CI minutes in GitLab CI (indirectly because CeCILL-B is not OSI-approved) and as a result, we only rely on one inria runner… which seems unstable, yielding randomly failing jobs such as:
https://gitlab.com/math-comp/docker-mathcomp/-/jobs/3721328523

I emailed Maxime in order to arrange some meeting to investigate/improve the situation…

**Comment by erikmd** [comment]
Incidentally, I just noticed that the tip of the master branch within gitlab is too old w.r.t. that of github:
* https://gitlab.com/math-comp/docker-mathcomp/-/commits/master?ref_type=heads
* https://github.com/math-comp/docker-mathcomp/commits/master
I'm investigate this ASAP, stay tuned…

**Comment by erikmd** [comment]
> I'm investigate this ASAP, stay tuned…

FYI it seems the automatic-pull-mirroring was disabled (I dunno why) in:

https://gitlab.com/math-comp/docker-mathcomp/-/settings/repository

It seems impossible to re-enable by a single click (I'll probably need to remove the gitlab repo and recreate it),
but in the meantime, I manually pushed to the current gitlab mirror repo, to trigger this pipeline:
https://gitlab.com/math-comp/docker-mathcomp/-/pipelines/768859375

Let me know if ever this pipeline fails because of the runner instability, I'll retry the jobs until we get an image of the release!

Cc @affeldt-aist @proux01

**Comment by proux01** [comment]
@erikmd thanks!
Indeed, the `prepare-config` job failed

**Comment by erikmd** [comment]
@proux01 thanks for the ping;
good news: [this pipeline](https://gitlab.com/math-comp/docker-mathcomp/-/pipelines/768931429) went through;
see also: https://hub.docker.com/r/mathcomp/mathcomp/tags?page=1&name=1.16.0

**Comment by proux01** [comment]
Wonderful!

**Pull request merged**
