### PR TITLE
New 1.19.0 release

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by proux01** [comment]
Ping @affeldt-aist or @erikmd I don't have the rights to merge this.

**Comment by erikmd** [comment]
Thanks @proux01 !
I will give you the missing rights on github for next time.

**Comment by erikmd** [comment]
Just FYI, the gitlab pipeline url is: https://gitlab.inria.fr/math-comp/docker-mathcomp/-/pipelines/910321

**Comment by pi8027** [comment]
Can we have Coq 8.19 images as well?

**Comment by proux01** [comment]
I guess they are building.

**Comment by proux01** [comment]
That's the very reason why we have to release a 1.19 and 2.2 for mathcomp, while the last release is barely two months old.

**Pull request merged**
