### PR TITLE
Add Mathcomp 2.2.0

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by pi8027** [comment]
`mathcomp/2.2.0-coq-dev` and `mathcomp-dev:coq-8.19` are still missing, or is it intentional?

**Comment by proux01** [comment]
I may have missed something, we will need @erikmd help there

**Comment by erikmd** [comment]
Thanks @proux01 for the merge;
I just pushed 2a4ec83181fbbf637e562fbc2f09b3be24c31586
Hence https://gitlab.inria.fr/math-comp/docker-mathcomp/-/pipelines/911869 is pending

**Comment by erikmd** [comment]
I will also manually update https://hub.docker.com/r/mathcomp/mathcomp#supported-tags from now on, by doing:
```
./external/docker-keeper/keeper.py write-artifacts
cat generated/README.md
```

**Comment by erikmd** [comment]
Question: what are all the stable mathcomp version compatible with coq 8.19 ? it seems there's not only 2.2.0

**Comment by erikmd** [comment]
(and 1.19.0 IINM)

so, thanks, that means that the current list @ https://hub.docker.com/r/mathcomp/mathcomp#supported-tags is complete

**Pull request merged**
